name: YAML - yamllint


on:
  workflow_call:
    inputs:
      runs_on:
        description: >
          JSON-encoded runs-on value.
          Examples:
          - '"ubuntu-latest"'
          - '["self-hosted","linux","x64"]'
        required: false
        type: string
        default: '"ubuntu-latest"'

      yamllint_version:
        type: string
        required: false
        default: latest
        description: "(Optional) The version of `yamllint` to install. Defaults to `latest`. Not implemented yet."
      yamllint_config_file:
        type: string
        required: false
        default: ".yamllint.yaml"
        description: "(Optional) The path to the `yamllint` config file. Defaults to `.yamllint.yaml`."
      yamllint_target_dir:
        type: string
        required: false
        default: ./
        description: "(Optional) A directory path to scan. Defaults to `./`."

    secrets:
      token:
        required: false
        description: "(Optional) The GitHub API token to use when communicating with GitHub API."


jobs:
  yamllint:
    name: Lint YAML files
    runs-on: ${{ fromJson(inputs.runs_on) }}

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v7

    - name: Install yamllint
      id: install-yamllint
      run: pip install yamllint

    - name: Lint YAML Files
      id: yaml-lint
      run: |
        yamllint \
          --format github \
          --config-file ${{ inputs.yamllint_config_file }} \
          ${{ inputs.yamllint_target_dir }}
